name: Network Intrustion Detector Environment
channels:
  - conda-forge
dependencies:
  - numpy
  - csv
  - os
  - shutil
  - psutil
  - toolz
  - matplotlib
  - dill
  - partd
  - bokeh
  - dask
  - scikit-learn
  - tensorflow
  - pip:
    - pandas

