name: Network Intrustion Detector Environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - partd
  - bokeh
  - dask
  - scikit-learn
  - tensorflow
  - pip 19.2.3:
    - pandas

