name: Network Intrustion Detector Environment
channels:
  - conda-forge
dependencies:
  - nodejs
  - numpy
  - pandas
  - psutil
  - toolz
  - matplotlib
  - ipywidgets
  - jupyter_contrib_nbextensions
  - dill
  - partd
  - bokeh
  - dask
  - scikit-learn
  - tensorflow
  - pip:
    - dask_labextension

